# Generated by Django 5.0 on 2023-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email adress')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('editor', 'Редактор'), ('moderator', 'Утолщенная вверху'), ('admin', 'Администратор')], default='user', max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
