# Generated by Django 5.0 on 2024-02-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='haed_color',
            new_name='head_color',
        ),
    ]
