# Generated by Django 5.0.2 on 2024-03-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroomimage',
            old_name='image',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='main.media'),
        ),
    ]
