# Generated by Django 5.0.2 on 2024-03-17 11:23

import main.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_haed_color_mushroom_head_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.SlugField(default=main.helpers.get_random_slug, max_length=32, unique=True),
        ),
    ]
